# Generated by Django 4.2.14 on 2024-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_I', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='doct_file_name',
            field=models.CharField(default='default_filename', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='document_path',
            field=models.CharField(default='file_path', max_length=255),
        ),
        migrations.AlterField(
            model_name='create_acc',
            name='Password',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
