# Generated by Django 4.2.14 on 2024-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_I', '0003_userdata_address_userdata_doct_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='doct_file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='document_path',
            field=models.CharField(max_length=255),
        ),
    ]
