# Generated by Django 4.2.14 on 2024-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_I', '0004_alter_userdata_address_alter_userdata_doct_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_acc',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
